name: Modulix Development
values:
  - key: baseUrl
    value: 'https://api-dev.modulix.example'
  - key: testUserEmail
    value: ''
  - key: testUserPassword
    value: ''
  - key: replacementUserPassword
    value: ''
  - key: updatedUserEmail
    value: ''
  - key: testUserId
    value: ''
  - key: userAccessToken
    value: ''
  - key: userRefreshToken
    value: ''
  - key: adminEmail
    value: ''
  - key: adminPassword
    value: ''
  - key: adminAccessToken
    value: ''
  - key: adminRefreshToken
    value: ''
  - key: adminTargetUserId
    value: ''
