name: Modulix Local
values:
  - key: baseUrl
    value: 'http://localhost:5284'
  - key: userAccessToken
    value: ''
  - key: adminAccessToken
    value: ''
  - key: moduleId
    value: ''
  - key: moduleName
    value: 'PostmanModule'
  - key: moduleDescription
    value: 'Disposable Postman test module.'
  - key: moduleBaseEndpointPath
    value: 'modules/postman'
  - key: moduleZipPath
    value: ''
  - key: moduleReplacementZipPath
    value: ''
  - key: moduleEndpointConfirmation
    value: '[]'
