name: Modulix Staging
values:
  - key: baseUrl
    value: 'https://api-staging.modulix.example'
  - key: testUserEmail
    value: ''
  - key: testUserPassword
    value: ''
  - key: replacementUserPassword
    value: ''
  - key: updatedUserEmail
    value: ''
  - key: testUserId
    value: ''
  - key: userAccessToken
    value: ''
  - key: userRefreshToken
    value: ''
  - key: adminEmail
    value: ''
  - key: adminPassword
    value: ''
  - key: adminAccessToken
    value: ''
  - key: adminRefreshToken
    value: ''
  - key: adminTargetUserId
    value: ''
  - key: moduleId
    value: ''
  - key: moduleName
    value: 'PostmanModule'
  - key: moduleDescription
    value: 'Disposable Postman test module.'
  - key: moduleBaseEndpointPath
    value: 'modules/postman'
  - key: moduleZipPath
    value: ''
  - key: moduleReplacementZipPath
    value: ''
  - key: moduleEndpointConfirmation
    value: '[]'
