name: Modulix Staging
values:
  - key: baseUrl
    value: 'https://api-staging.modulix.example'
  - key: userAccessToken
    value: ''
  - key: adminAccessToken
    value: ''
  - key: moduleId
    value: ''
  - key: moduleName
    value: 'PostmanModule'
  - key: moduleDescription
    value: 'Disposable Postman test module.'
  - key: moduleBaseEndpointPath
    value: 'modules/postman'
  - key: moduleZipPath
    value: ''
  - key: moduleReplacementZipPath
    value: ''
  - key: moduleEndpointConfirmation
    value: '[]'
