<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Modulix - Abstraction</AssemblyTitle>
    <RootNamespace>$(MSBuildProjectName.Replace(".Abstraction", ""))</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Title>Modulix - Abstraction</Title>
    <Authors>Max Meyer</Authors>
    <Product>Modulix</Product>
    <Description>Abstraction library for the Modulix HTTP client.</Description>
    <PackageTags>Modulix;HttpClient;Abstraction</PackageTags>
    <RepositoryUrl>https://github.com/MaxMeyer-05/Modulix</RepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <Version>1.0.0</Version>
    <FileVersion>1.0.1</FileVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="readme.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
